# Generated by Django 5.0.2 on 2024-07-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('laptop_name', models.CharField(max_length=50)),
                ('laptop_model', models.CharField(max_length=50)),
                ('laptop_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('LED_name', models.CharField(max_length=50)),
                ('LED_model', models.CharField(max_length=50)),
                ('LED_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('mobile_name', models.CharField(max_length=50)),
                ('mobile_model', models.CharField(max_length=50)),
                ('mobile_price', models.CharField(max_length=100)),
            ],
        ),
    ]
